//
//  BMPaintCode.h
//  ProjectName
//
//  Created by Alminty on 1/2/16.
//  Copyright (c) 2016 Alminty. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BMPaintCode : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconWriteBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconHomeBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconProfileBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconWriteSelectedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconProfileSelectedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconHomeSelectedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconBackBlackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconOfLogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconSubmitBlackTargets;

// Colors
+ (UIColor*)color;
+ (UIColor*)fill;

// Generated Images
+ (UIImage*)imageOfIconWriteBlack;
+ (UIImage*)imageOfIconHomeBlack;
+ (UIImage*)imageOfIconProfileBlack;
+ (UIImage*)imageOfIconWriteSelected;
+ (UIImage*)imageOfIconProfileSelected;
+ (UIImage*)imageOfIconHomeSelected;
+ (UIImage*)imageOfIconBackBlack;
+ (UIImage*)imageOfIconOfLogo;
+ (UIImage*)imageOfIconSubmitBlack;

@end
